"""Insert da tabela usuario

Revision ID: 1e8fd6954e69
Revises: a44d7f17f8ce
Create Date: 2023-09-14 20:17:55.255301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8fd6954e69'
down_revision: Union[str, None] = 'a44d7f17f8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('endereco_eletronico', sa.String(), nullable=False))
    op.drop_column('usuario', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('usuario', 'endereco_eletronico')
    # ### end Alembic commands ###
