"""Inicial

Revision ID: 78cfd388ec78
Revises: 
Create Date: 2023-09-14 11:18:12.242912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78cfd388ec78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_loja', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('rua', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('horario_funcionamento', sa.String(), nullable=False),
    sa.Column('pontos_interesse', sa.String(), nullable=False),
    sa.Column('resumo_estabelecimento', sa.String(), nullable=False),
    sa.Column('link_site_rede_social', sa.String(), nullable=False),
    sa.Column('imagem', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usarname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('hashed_senha', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('usuario_tipo', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('usuario_id', name='usuarios_pkey')
    )
    op.drop_table('loja')
    # ### end Alembic commands ###
