"""Insert da tabela usuario

Revision ID: a44d7f17f8ce
Revises: 78cfd388ec78
Create Date: 2023-09-14 20:16:40.752458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44d7f17f8ce'
down_revision: Union[str, None] = '78cfd388ec78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_loja', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('rua', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('horario_funcionamento', sa.String(), nullable=False),
    sa.Column('pontos_interesse', sa.String(), nullable=False),
    sa.Column('resumo_estabelecimento', sa.String(), nullable=False),
    sa.Column('link_site_rede_social', sa.String(), nullable=False),
    sa.Column('imagem', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('tipo_usuario', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('loja')
    # ### end Alembic commands ###
