"""correcao

Revision ID: de47d70e656e
Revises: 
Create Date: 2023-10-29 17:59:45.247959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de47d70e656e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loja',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_loja', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('rua', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('horario_funcionamento', sa.String(), nullable=True),
    sa.Column('pontos_interesse', sa.String(), nullable=True),
    sa.Column('resumo_estabelecimento', sa.String(), nullable=True),
    sa.Column('link_site_rede_social', sa.String(), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('tipo_usuario', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('loja')
    # ### end Alembic commands ###
