"""Insert da tabela usuario

Revision ID: e85c18902bc4
Revises: 1e8fd6954e69
Create Date: 2023-09-14 20:18:56.106194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85c18902bc4'
down_revision: Union[str, None] = '1e8fd6954e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('email', sa.String(), nullable=False))
    op.drop_column('usuario', 'endereco_eletronico')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('endereco_eletronico', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('usuario', 'email')
    # ### end Alembic commands ###
